name: ptjpl
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11
  - conda>=23.5.2
  - setuptools
  - pip
  - wheel
  - scipy
  - numpy
  - h5netcdf
  - netcdf4
  - h5py
  - xarray
  - rasterio
  - requests
